# Generated by Django 2.2 on 2019-04-28 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_credentialobjectstorage_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.DecimalField(blank=True, decimal_places=31, default=None, max_digits=32, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='accuracy',
        ),
        migrations.AddField(
            model_name='project',
            name='is_updating_acc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credentialobjectstorage',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='SampleFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(default=0)),
                ('accuracy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Accuracy')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Label')),
            ],
        ),
        migrations.AddField(
            model_name='accuracy',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project'),
        ),
    ]
