version: 1
jobs:
  build:
    working_directory: ~/pfe
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: pfe_2018
      - image: circleci/redis:5.0.4
    steps:
      - checkout
      - run:
          command: |
            cd backend
            sudo pip install pipenv
            pipenv install
            pipenv run celery -A main worker -l info -E &
            pipenv run python manage.py test
